# Config file for iproto

# Consensus widget
	numberOfNodes = 19
	numberOfMoneyBags = 17
	consensusDelay = 1500 # milliseconds
	moneyBagsDelay = 40 # milliseconds

# SGX monitor widget (logger)
	loggerDelay   = 2000 # milliseconds
	loggerRefresh = 5

#	Gauge widget
	gaugeDelay    = 1 # millisecond
	endGaugeWait  = 500 # milliseconds
	gaugeInterval = 1

# Parameters for generating transactions for gauge widget
	maxTransactions = 2100
	randFactor      = 297

# Left side: Relative size of gauge vs. consensus windows
	splitPercentLeft = 15

	# Right side: relative size of top 2 vs. bottom
	splitPercentRight = 70

# Relative size left vs. right side of screen
	splitPercentVertical = 50
