#!/usr/bin/env bash

BALANCE_TABLE="BALANCE"
TRANSACTION_TABLE="TRANSACTION"
ACCOUNT_TABLE="ACCOUNT"
WORDS_TABLE="WORDS"

DATABASE="Infinigon"

cockroach version

echo ; echo -n "Creating Infinigon Database..."

cockroach sql --execute="CREATE DATABASE IF NOT EXISTS $DATABASE" >/dev/null

echo "done."

echo -n "Adding new user (donaldww)..."
cockroach user set donaldww >/dev/null
echo "done." ; echo
cockroach user ls
echo

# Drop Tables
cockroach sql --insecure --execute="DROP TABLE IF EXISTS ${TRANSACTION_TABLE}"
cockroach sql --insecure --execute="DROP TABLE IF EXISTS ${BALANCE_TABLE}"
cockroach sql --insecure --execute="DROP TABLE IF EXISTS ${ACCOUNT_TABLE}"

echo

cockroach sql --insecure --execute="
	CREATE TABLE IF NOT EXISTS ${ACCOUNT_TABLE}
	(
		public_id STRING PRIMARY KEY UNIQUE,    /* the public address */
		system_id UUID UNIQUE,                  /* this id will appear in transactions */
		ip INET,
		email STRING,
        registration_date DATE
	)"

# Create Tables
cockroach sql --insecure --execute="
	CREATE TABLE IF NOT EXISTS ${BALANCE_TABLE}
	(
		public_id STRING PRIMARY KEY UNIQUE REFERENCES ${ACCOUNT_TABLE} (public_id),
		system_id UUID UNIQUE REFERENCES ${ACCOUNT_TABLE} (system_id),

		balance FLOAT8,
		CHECK (balance >= 0),

		fuel FLOAT,
		CHECK (balance >=0),

		nonce INT,
		CHECK (nonce >= 0)
	)"

cockroach sql --insecure --execute="
	CREATE TABLE IF NOT EXISTS ${TRANSACTION_TABLE}
	(
		transaction_id UUID PRIMARY KEY UNIQUE, /* generated by the transaction by the wallet */

		from_address STRING REFERENCES balance (public_id),
		to_address STRING REFERENCES balance (public_id),

		amount FLOAT8,
		CHECK (amount >= 0),

		timestamp TIMESTAMPTZ
	)"

