#! /usr/bin/env bash

export INFINIGON_HOME=/usr/local/infinigon
export INFINIGON_BIN=$INFINIGON_HOME/bin
export INFINIGON_DEMO=$INFINIGON_HOME/demo

cp $INFINIGON_DEMO/ig17-good/ig17-core $INFINIGON_BIN/ig17-core
clear
echo
echo "Infingon core installed into Intel SGX environment."
echo
